### ISSUE TITLE
nil pointer on Events timeouts 

### ISSUE THREAD

**Issue by spolti** [serverlessworkflow/sdk-go#107]
**What happened**:
While trying to parse a workflow file the event timeouts (all types) was getting a nil pointer.

**What you expected to happen**:
The parsed timeout values.

**How to reproduce it**:
Create a workflow with events timeouts and try to parse it  using the FromFile func.
e.g.:
```
  - name: ParallelExec
    type: parallel
    completionType: allOf
    branches:
      - name: ShortDelayBranch
        actions:
          - subFlowRef: shortdelayworkflowid
        actionExecTimeout: "PT5H"
        branchExecTimeout: "PT6M"
      - name: LongDelayBranch
        actions:
          - subFlowRef: longdelayworkflowid
    timeouts:
      branchExecTimeout: "PT6M"
      stateExecTimeout:
        total: PT1S
        single: PT2S
```

And when trying to assert them, a nil would happen:
```
assert.Equal(t, "PT5H", w.States[2].(*model.ParallelState).Branches[0].Timeouts.ActionExecTimeout)
assert.Equal(t, "PT6M", w.States[2].(*model.ParallelState).Branches[0].Timeouts.BranchExecTimeout)
```				

**Anything else we need to know?**:

**Environment**:
- Specification version used:

- Go version:
