### ISSUE TITLE
Switch types custom UnmarshalJSON only partially implemented.

### ISSUE THREAD

**Issue by alankm** [serverlessworkflow/sdk-go#16]
**What happened**:

I unmarshaled a complex document from JSON, and then attemped to access a field but it caused a panic.

Upon further investigation, I discovered that two structs with custom `UnmarshalJSON` functions only handle the unmarshalling of a single field, everything else is discarded.

**What you expected to happen**:

I expected to have full programmatic access to every field provided in the document.

**How to reproduce it**:

```yaml
id: applicantrequest
version: '1.0'
name: Applicant Request Decision Workflow
description: Determine if applicant request is valid
functions:
- name: sendRejectionEmailFunction
  operation: http://myapis.org/applicationapi.json#emailRejection
states:
- name: CheckApplication
  type: switch
  start:
    kind: default
  dataConditions:
  - condition: "{{ $.applicants[?(@.age >= 18)] }}"
    transition:
      nextState: StartApplication
  - condition: "{{ $.applicants[?(@.age < 18)] }}"
    transition:
      nextState: RejectApplication
  default:
    transition:
      nextState: RejectApplication
- name: StartApplication
  type: subflow
  workflowId: startApplicationWorkflowId
  end:
    kind: default
- name: RejectApplication
  type: operation
  actionMode: sequential
  actions:
  - functionRef:
      refName: sendRejectionEmailFunction
      parameters:
        applicant: "{{ $.applicant }}"
  end:
    kind: default
```

```go
package main

import (
    "fmt"

    "github.com/serverlessworkflow/sdk-go/parser"
)

func main() {

    wf, err := parser.FromFile("wf.yml")
    if err != nil {
        panic(err)
    }

    // works
    fmt.Printf("Stage %v\n", wf.States[1].GetName())

    // switch, does not work
    fmt.Printf("Stage %v\n", wf.States[0].GetName())

}
```

**Anything else we need to know?**:

-

**Environment**:
- Specification version used: 1.0.0

- Go version: 1.15.4
