### ISSUE TITLE
JSON or as a YAML file: workflow.states must be int32

### ISSUE THREAD

**Issue by spolti** [serverlessworkflow/sdk-go#177]
**What happened**:
When there is a boolean value in the Data field of the Inject State:
```
  - name: HelloInject
    type: inject
    data:
      result: Hello World, last state!
      boolValue: false
```

**What you expected to happen**:
Workflow be successfully parsed.

**How to reproduce it**:
Add any boolean value for Inject State Data field, as the example above.

**Anything else we need to know?**:

**Environment**:
- Specification version used:

- Go version:
