### ISSUE TITLE
Implement a simple data flow and JQ expression processing

### ISSUE THREAD

**Issue by ricardozanini** [serverlessworkflow/sdk-go#222]
As a start to have the base reference implementation, it should validate the `do` scenario listed in the CTK https://github.com/serverlessworkflow/specification/blob/main/ctk/features/set.feature.

Essentially, it is a basic flow with the `Set` task and JQ data processing.

Example:

```yaml
    document:
      dsl: '1.0.0-alpha5'
      namespace: default
      name: set
      version: '1.0.0'
    do:
      - setShape:
          set:
            shape: circle
            size: ${ .configuration.size }
            fill: ${ .configuration.fill }
```
