### ISSUE TITLE
Add Run Container to the reference implementation

### ISSUE THREAD

**Issue by ricardozanini** [serverlessworkflow/sdk-go#223]
Depends on #222 

Use the following example to run containers from the reference implementation:

```yaml
document:
  dsl: '1.0.0-alpha5'
  namespace: test
  name: run-container
  version: '0.1.0'
do:
  - runContainer:
      run:
        container:
          image: hello-world
```
