### ISSUE TITLE
Add support to the `call http` task

### ISSUE THREAD

**Issue by ricardozanini** [serverlessworkflow/sdk-go#230]
**What would you like to be added**:
Moving forward with the implementation, we need to add the `call http` task for more compelling demos.

We can use this to verify this work:
- https://github.com/serverlessworkflow/specification/blob/main/ctk/features/call.feature
- https://github.com/serverlessworkflow/specification/blob/main/examples/call-http-endpoint-interpolation-shorthand.yaml
- https://github.com/serverlessworkflow/specification/blob/main/examples/call-http-endpoint-interpolation.yaml
- https://github.com/serverlessworkflow/specification/blob/main/examples/call-http-query-headers-expressions.yaml
- https://github.com/serverlessworkflow/specification/blob/main/examples/call-http-redirect.yaml

Authorization is out of the scope now.

**Comment by fjtirado** [comment]
@thepabloaguilar yes, the issue consist on implementing the Run method. 
Feel free to try ;)

**Comment by thepabloaguilar** [comment]
Hi all, I was implementing it here and something came up when I saw this example:
```yaml
document:
      dsl: '1.0.1'
      namespace: default
      name: http-call-with-basic-auth
      version: '1.0.0'
    do:
      - login:
          call: http
          with:
            method: get
            endpoint:
              uri: https://httpbin.org/basic-auth/{username}/{password}
              authentication:
                basic:
                  username: ${ .username }
                  password: ${ .password }
```

The `username: ${ .username }` part we can use `expr.TraverseAndEvaluate` but when dealing if `uri: https://httpbin.org/basic-auth/{username}/{password}` we can't, how can we resolve those variables?

> Sorry for asking that, I'm not used to the project yet
