### ISSUE TITLE
Update support to v0.8

### ISSUE THREAD

**Issue by brlala** [serverlessworkflow/sdk-go#70]
**What would you like to be added**:
Update to v0,8

**Why is this needed**:
V0.8 has lots of new enhancements like async subflow and custom function. All other SDK has already been updated, should this be done as well?

**Comment by ricardozanini** [comment]
@brlala, it's on our roadmap to upgrade. We are looking for contributions :)

**Comment by lsytj0413** [comment]
@ricardozanini I'd like to take care of this, because I am reviewing all the existing verifications, relevant to this feature.

**Comment by ricardozanini** [comment]
@lsytj0413 that's perfectly fine from my side.

**Comment by spolti** [comment]
Hi all, I'll he helping on this task in the next few days.

The spec for reference: https://github.com/serverlessworkflow/specification/tree/0.8.x/roadmap#-release-version-08

The table below is to help us to track what needs to be completed:

| Status | Description | Comments |
| --- | --- | --- |
| :exclamation:| Support custom function `type` definition |
| :exclamation: | Workflow "name" no longer a required property | 
| :exclamation: | Workflow "start" no longer a required property |
| :exclamation: | ForEach state "iterationParam" no longer a required property | 
| :exclamation: | Added "useData" for eventDataFilter, and "useResults" for actionDataFilter | 
| :exclamation: | Added "resultEventTimeout" for action eventref | 
| :exclamation: | Added example for "continueAs" |
| :exclamation: | Support for async action invocation |
| :exclamation: | Support for action condition |


If there is a task already added, please let me. If possible attach the pull request in this issue.

Thanks.

**Comment by lsytj0413** [comment]
@spolti  I'm working on `Added "useData" for eventDataFilter, and "useResults" for actionDataFilter`

**Comment by spolti** [comment]
Thanks for the update @lsytj0413.

**Comment by spolti** [comment]
@lsytj0413 for the item you was working on, in the PR that was merged you have added only the useData, are you going to send another pr for the useResults field?

**Comment by lsytj0413** [comment]
> @lsytj0413 for the item you was working on, in the PR that was merged you have added only the useData, are you going to send another pr for the useResults field?

Yep, i'm working on another PR to add `useResults` field.

**Comment by spolti** [comment]
probably closed by my mistake :D
@ricardozanini can you please re-open?

**Comment by spolti** [comment]
For the `Added example for "continueAs"` item, there isn't much to do, however there is no test to validate it.
While adding a test it turns out that the `data` field is always nil, for example:

```yaml
 - name: CheckEventQuota
   type: switch
   dataConditions:
    - condition: "${ try(.customerCount) != null and .customerCount > .quota.maxConsumedEvents
      }"
      end:
       continueAs:
        workflowId: notifycustomerworkflow
        version: '1.0'
        data: "${ del(.customerCount) }"
```

I am looking over it to figure out why.
